wiki:
  index_url: http://35.246.221.26:8000
  annotator_url: https://spike-annotation.en.apps.allenai.org
  matching_graph_representation: universal-enhanced
  expansion_graph_representation: universal-basic
  annotator_propagate_coref_info: false